###
POST https://login.remita.net/remita/exapp/api/v1/send/api

content-type: application/json

{
    "username": "eruditeprogrammer@yahoo.com",
    "password": "Mnijoiafesremita147/"
}

###
GET http://localhost:8090/backup/production 