// regNumber: String,
//   email: String,
//   sex: String,
//   name: String,
//   dept: String,
//   faculty: String,
//   phoneNumber: String,
//   currentLevel: String,
//   currentSession: String,
//   nextOfKin: {
//     name: { type: String, required: false },
//     address: { type: String, required: false },
//     phone: { type: String, required: false },
//   },
//   entryMode: String,

const students = [
  {
    regNumber: "01/55/EE/044",
    email: "jamiebones2000@yahoo.co.uk",
    sex: "Male",
    name: "Johnny Brasco",
    dept: "Chemistry",
    faculty: "Science",
    phoneNumber: "08056566666",
    currentLevel: "100 level",
    currentSession: "2020/2021",
    entryMode: "utme",
    nextofKin: {
      name: "posaco manosbeen",
      address: "flavour avenue coast to coast",
      phone: "08939383839",
    },
    profileImage: "https://homepages.cae.wisc.edu/~ece533/images/girl.png",
  },

  {
    regNumber: "01/55/EE/045",
    email: "jamiebones200@yahoo.co.uk",
    sex: "Female",
    name: "Caroline Imokon",
    dept: "Biology Education",
    faculty: "Education",
    phoneNumber: "08056566666",
    currentLevel: "400 level",
    currentSession: "2020/2021",
    entryMode: "utme",
    nextofKin: {
      name: "posaco manosbeen",
      address: "flavour avenue coast to coast",
      phone: "08939383839",
    },
    profileImage: "https://homepages.cae.wisc.edu/~ece533/images/girl.png",
  },

  {
    regNumber: "01/55/EE/046",
    email: "jamiebones20@yahoo.co.uk",
    sex: "Male",
    name: "Mamode Positerity",
    dept: "Chemical Engineering",
    faculty: "Engineering",
    phoneNumber: "08056566666",
    currentLevel: "200 level",
    currentSession: "2020/2021",
    entryMode: "direct entry",
    nextofKin: {
      name: "posaco manosbeen",
      address: "flavour avenue coast to coast",
      phone: "08939383839",
    },
    profileImage: "https://homepages.cae.wisc.edu/~ece533/images/girl.png",
  },

  {
    regNumber: "01/55/EE/088",
    email: "flamers@flame.com",
    sex: "Male",
    name: "Johnny Brasco",
    dept: "Medicine & Surgery",
    faculty: "Clinical Sciences",
    phoneNumber: "08056566666",
    currentLevel: "200 level",
    currentSession: "2020/2021",
    entryMode: "utme",
    nextofKin: {
      name: "posaco manosbeen",
      address: "flavour avenue coast to coast",
      phone: "08939383839",
    },
    profileImage: "https://homepages.cae.wisc.edu/~ece533/images/girl.png",
  },

  {
    regNumber: "01/55/EE/099",
    email: "flamers56@flame.com",
    sex: "Male",
    name: "Johnny Brasco",
    dept: "Medicine & Surgery",
    faculty: "Clinical Sciences",
    phoneNumber: "08056566666",
    currentLevel: "500 level",
    currentSession: "2020/2021",
    entryMode: "utme",
    nextofKin: {
      name: "posaco manosbeen",
      address: "flavour avenue coast to coast",
      phone: "08939383839",
    },
    profileImage: "https://homepages.cae.wisc.edu/~ece533/images/girl.png",
  },
  {
    regNumber: "01/55/EE/070",
    email: "jamiebones@yahoo.co.uk",
    sex: "Male",
    name: "Johnny Brasco",
    dept: "Chemistry",
    faculty: "Law",
    phoneNumber: "08056566666",
    currentLevel: "100 level",
    currentSession: "2020/2021",
    entryMode: "utme",
    nextofKin: {
      name: "posaco manosbeen",
      address: "flavour avenue coast to coast",
      phone: "08939383839",
    },
    profileImage: "https://homepages.cae.wisc.edu/~ece533/images/girl.png",
  },
];

export default students;
