export default {
  Replica_Set_One: process.env.Replica_Set_One,
  Replica_Set_Two: process.env.Replica_Set_Two,
  Replica_Set_Three: process.env.Replica_Set_Three,
  DB_HOST: process.env.DB_HOST,
  DB_PORT: process.env.DB_PORT,
  DB_USER: process.env.DB_USER,
  DB_DATABASE: process.env.DB_DATABASE,
  DB_PASSWORD: process.env.DB_PASSWORD,
  REDIS_URL: process.env.REDIS_URL,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  SMS_API: process.env.SMS_API,
  SMS_Token: process.env.SMS_Token,
  REMITA_PUBLIC_KEY: process.env.REMITA_PUBLIC_KEY,
  REMITA_SECRET_KEY: process.env.REMITA_SECRET_KEY,
  MerchantId: process.env.MerchantId,
  Api_Key: process.env.Api_Key,
  ServiceTypeId: process.env.ServiceTypeId,
  Gateway: process.env.Gateway,
  CheckStatusUrl: process.env.CheckStatusUrl,
  ReturnRemitaUrl: process.env.ReturnRemitaUrl,
  RRRGateWayPaymentUrl: process.env.RRRGateWayPaymentUrl,
  JusibePublicKey: process.env.JusibePublicKey,
  JusibeAccessToken: process.env.JusibeAccessToken,
  EBulkSMSAPIKey: process.env.EBulkSMSAPIKey,
  EBulkSMSUsername: process.env.EBulkSMSUsername,
  EBulkSMSGateWay: process.env.EBulkSMSGateWay,
  CheapGlobalSmsGateway: process.env.CheapGlobalSmsGateway,
  CheapGlobalSmsSubAccount: process.env.CheapGlobalSmsSubAccount,
  CheapGlobalSmsSubAccountPassword:
    process.env.CheapGlobalSmsSubAccountPassword,
  DeveloperBugsEmailSupport: process.env.DeveloperBugsEmailSupport,
  DeveloperBugsEmailPassword: process.env.DeveloperBugsEmailPassword,
  ME_CONFIG_MONGODB_SERVER: process.env.ME_CONFIG_MONGODB_SERVER,
  ME_CONFIG_MONGODB_ADMINUSERNAME: process.env.ME_CONFIG_MONGODB_ADMINUSERNAME,
  ME_CONFIG_MONGODB_ADMINPASSWORD: process.env.ME_CONFIG_MONGODB_ADMINPASSWORD,
  ME_CONFIG_BASICAUTH_USERNAME: process.env.ME_CONFIG_BASICAUTH_USERNAME,
  ME_CONFIG_BASICAUTH_PASSWORD: process.env.ME_CONFIG_BASICAUTH_PASSWORD,
  VIRTUAL_HOST: process.env.VIRTUAL_HOST,
  LETSENCRYPT_HOST: process.env.LETSENCRYPT_HOST,
  LETSENCRYPT_EMAIL: process.env.LETSENCRYPT_EMAIL,
};
